[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hello"
version = "0.1.0"
description = "Your package description"
authors = [
    { name="Your Name", email="you@example.com" }
]
dependencies = []
