name: Release Please

on:
  push:
    branches:
      - main  # or 'master' or your default branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: python  # or python, rust, go, etc.
          token: ${{ secrets.GITHUB_TOKEN }}
