name: Release Please

on:
  push:
    branches:
      - main  # or 'master' or your default branch
permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action
        with:
          release-type: python  # or python, rust, go, etc.
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
